In [106]:
import pandas as pd

In [107]:
#Load CSV File
students = pd.read_csv('students.csv')
students

   roll   name          course   fees    city
0     1   Amit          Python  25000    Pune
1     2   Neha    Data Science  45000  Mumbai
2     3  Rahul          Python  25000  Nagpur
3     4  Priya            Java  30000    Pune
4     5  Rohan  Data Analytics  40000  Nashik
5     6  Sneha            Java  30000  Mumbai
6     7  Karan          Python  25000    Pune
7     8  Pooja    Data Science  45000  Nagpur
8     9   Ajay  Data Analytics  40000    Pune
9    10  Meena            Java  30000  Nashik

In [108]:
# Access Columns

students['name']
students[['name','course']]
students['fees']
students.dtypes[['roll','name','course','fees','city']]

roll      int64
name        str
course      str
fees      int64
city        str
dtype: object

In [109]:
#  Access Rows
students.head(5)
students.tail(4)
students.iloc[3]
students.iloc[2:7]

   roll   name          course   fees    city
2     3  Rahul          Python  25000  Nagpur
3     4  Priya            Java  30000    Pune
4     5  Rohan  Data Analytics  40000  Nashik
5     6  Sneha            Java  30000  Mumbai
6     7  Karan          Python  25000    Pune

In [110]:
# Add New Column
students['gst']= students['fees'] * 0.18
students[['fees','gst']]

    fees     gst
0  25000  4500.0
1  45000  8100.0
2  25000  4500.0
3  30000  5400.0
4  40000  7200.0
5  30000  5400.0
6  25000  4500.0
7  45000  8100.0
8  40000  7200.0
9  30000  5400.0

In [111]:
# Calculate New Column
students['total_fees'] = students['fees'] + students['gst']
students[['fees','gst','total_fees']]

    fees     gst  total_fees
0  25000  4500.0     29500.0
1  45000  8100.0     53100.0
2  25000  4500.0     29500.0
3  30000  5400.0     35400.0
4  40000  7200.0     47200.0
5  30000  5400.0     35400.0
6  25000  4500.0     29500.0
7  45000  8100.0     53100.0
8  40000  7200.0     47200.0
9  30000  5400.0     35400.0

In [112]:
# Add New Row
students.loc[len(students)] = [1,'Vaibhav','AWS',35000,'Pune',6400.0,41400.0]
students

    roll     name          course   fees    city     gst  total_fees
0      1     Amit          Python  25000    Pune  4500.0     29500.0
1      2     Neha    Data Science  45000  Mumbai  8100.0     53100.0
2      3    Rahul          Python  25000  Nagpur  4500.0     29500.0
3      4    Priya            Java  30000    Pune  5400.0     35400.0
4      5    Rohan  Data Analytics  40000  Nashik  7200.0     47200.0
5      6    Sneha            Java  30000  Mumbai  5400.0     35400.0
6      7    Karan          Python  25000    Pune  4500.0     29500.0
7      8    Pooja    Data Science  45000  Nagpur  8100.0     53100.0
8      9     Ajay  Data Analytics  40000    Pune  7200.0     47200.0
9     10    Meena            Java  30000  Nashik  5400.0     35400.0
10     1  Vaibhav             AWS  35000    Pune  6400.0     41400.0

In [113]:
# Rename Columns
students=students.rename(columns={'name':'student_name','fees':'course_fee','city':'location'})
students

    roll student_name          course  course_fee location     gst  total_fees
0      1         Amit          Python       25000     Pune  4500.0     29500.0
1      2         Neha    Data Science       45000   Mumbai  8100.0     53100.0
2      3        Rahul          Python       25000   Nagpur  4500.0     29500.0
3      4        Priya            Java       30000     Pune  5400.0     35400.0
4      5        Rohan  Data Analytics       40000   Nashik  7200.0     47200.0
5      6        Sneha            Java       30000   Mumbai  5400.0     35400.0
6      7        Karan          Python       25000     Pune  4500.0     29500.0
7      8        Pooja    Data Science       45000   Nagpur  8100.0     53100.0
8      9         Ajay  Data Analytics       40000     Pune  7200.0     47200.0
9     10        Meena            Java       30000   Nashik  5400.0     35400.0
10     1      Vaibhav             AWS       35000     Pune  6400.0     41400.0

In [114]:
# Filtering

# Single Condition
students[students['location']=='Pune']
students[students['course_fee']>30000]

# Multiple Conditions
students[(students['location'] == 'Pune') & (students['course_fee']>25000)]
students[(students['location'] == 'Mumbai') | (students['course']=='Java')]
students[(students['location'] == 'Nagpur') & (students['course']=='Data Science')]

   roll student_name        course  course_fee location     gst  total_fees
7     8        Pooja  Data Science       45000   Nagpur  8100.0     53100.0

In [115]:
# Sorting
students.sort_values(by='course_fee')
students.sort_values(by='course_fee', ascending=False)
students.sort_values(by=['location','course_fee'])

    roll student_name          course  course_fee location     gst  total_fees
5      6        Sneha            Java       30000   Mumbai  5400.0     35400.0
1      2         Neha    Data Science       45000   Mumbai  8100.0     53100.0
2      3        Rahul          Python       25000   Nagpur  4500.0     29500.0
7      8        Pooja    Data Science       45000   Nagpur  8100.0     53100.0
9     10        Meena            Java       30000   Nashik  5400.0     35400.0
4      5        Rohan  Data Analytics       40000   Nashik  7200.0     47200.0
0      1         Amit          Python       25000     Pune  4500.0     29500.0
6      7        Karan          Python       25000     Pune  4500.0     29500.0
3      4        Priya            Java       30000     Pune  5400.0     35400.0
10     1      Vaibhav             AWS       35000     Pune  6400.0     41400.0
8      9         Ajay  Data Analytics       40000     Pune  7200.0     47200.0

In [116]:
# Create Another CSV
#payments.csv
payments=pd.read_csv('payments.csv')

In [117]:
# merge operation
student_data =pd.merge(students,payments,how='inner',on='roll')
pd.merge(students,payments,how='left',on='roll')
pd.merge(students,payments,how='right',on='roll')
pd.merge(students,payments,how='outer',on='roll')

,roll,student_name,course,course_fee,location,gst,total_fees,paid_fees
0,1,Amit,Python,25000,Pune,4500.0,29500.0,20000
1,1,Vaibhav,AWS,35000,Pune,6400.0,41400.0,20000
2,2,Neha,Data Science,45000,Mumbai,8100.0,53100.0,40000
3,3,Rahul,Python,25000,Nagpur,4500.0,29500.0,25000
4,4,Priya,Java,30000,Pune,5400.0,35400.0,25000
5,5,Rohan,Data Analytics,40000,Nashik,7200.0,47200.0,35000
6,6,Sneha,Java,30000,Mumbai,5400.0,35400.0,30000
7,7,Karan,Python,25000,Pune,4500.0,29500.0,15000
8,8,Pooja,Data Science,45000,Nagpur,8100.0,53100.0,45000
9,9,Ajay,Data Analytics,40000,Pune,7200.0,47200.0,30000
10,10,Meena,Java,30000,Nashik,5400.0,35400.0,28000

In [118]:
# Remaining Fees Calculation
remaing_fee =student_data['remaining_fees'] = student_data['course_fee'] - student_data['paid_fees']
student_data[['student_name','course_fee','paid_fees','remaining_fees']]

   student_name  course_fee  paid_fees  remaining_fees
0          Amit       25000      20000            5000
1          Neha       45000      40000            5000
2         Rahul       25000      25000               0
3         Priya       30000      25000            5000
4         Rohan       40000      35000            5000
5         Sneha       30000      30000               0
6         Karan       25000      15000           10000
7         Pooja       45000      45000               0
8          Ajay       40000      30000           10000
9         Meena       30000      28000            2000
10      Vaibhav       35000      20000           15000

In [123]:
#  Complex Filtering

remaing_fee =student_data['remaining_fees'] = student_data['course_fee'] - student_data['paid_fees']
students[remaing_fee >5000]

students[(students['location'] == 'pune') & (remaing_fee >5000)]
student_data[(student_data['course'] == 'Python') & (student_data['paid_fees'] < 20000)]
#students[(students['location'] == 'Mumbai') | (students['location'] == 'Nagpur') & (students['course_fee'] > 30000)]

,roll,student_name,course,course_fee,location,gst,total_fees,paid_fees,remaining_fees
6,7,Karan,Python,25000,Pune,4500.0,29500.0,15000,10000